services:
  innkeeper:
    build: ./innkeeper
    container_name: innkeeper
    environment:
      DATABASE_URL: postgres://dragontap:dragontap@cellar:5432/dragontap
    ports:  
      - "4181:4181"
    depends_on:
      - cellar
    networks:
      - dragontap-net
      
  cellar:
    image: postgres:16-alpine
    container_name: cellar
    environment: 
      POSTGRES_DB: dragontap 
      POSTGRES_USER: dragontap 
      POSTGRES_PASSWORD: dragontap 
    ports: 
      - "4183:5432"
    volumes :
     - dragontapdata:/var/lib/postgresql/data 
    networks:
      - dragontap-net
  board: 
    build: ./board
    container_name: board
    ports:  
      - "4182:4182"
    depends_on:
      - innkeeper
    networks:
      - dragontap-net

volumes:
  dragontapdata:
networks:
  - dragontap-net:
